[project]
name = "lazrs"
version = "0.6.3"
classifier = [
  "Intended Audience :: Developers",
  "Programming Language :: Python",
  "Programming Language :: Rust",
]


[build-system]
requires = ["maturin>=1.0.0,<2.0.0"]
build-backend = "maturin"
